site_name: "Techniques for supporting Indigenous language characters in  B.C. government systems"
site_description: "Techniques for supporting Indigenous language characters in  B.C. government systems."
docs_dir: "docs"
plugins:
    - techdocs-core
    - ezlinks

markdown_extensions:
    - markdown_inline_mermaid
    - md_in_html
    -   mkpatcher:
            location: patcher.py

#          Example navigation structure shown below. Fill out as appropriate for your content.
nav:
    -   Overview: index.md
    -   Databases:
            - Databases and Unicode: databases/Readme
            - Db2: databases/db2/db2
            - mysql: databases/mysql/mysql
            - Oracle: databases/oracle/oracle
            - PostgreSQL: databases/postgresql/postgresql
            - SQL Server: databases/sqlserver/sqlserver
    -   Programming languages:
            - Programming languages and Unicode: programming_languages/Readme
            - C: programming_languages/c/Readme.md
            - C++: programming_languages/c++/Readme.md
            - cobol: programming_languages/cobol/README.md
            - go: programming_languages/go/README.md
            - java: programming_languages/java/README.md
            - javascript: programming_languages/javascript/README.md
            - nodejs: programming_languages/nodejs/README.md
            - perl: programming_languages/perl/README.md
            - php: programming_languages/php/README.md
            - python2: programming_languages/python2/README.md
            - python3: programming_languages/python3/README.md
    -   COTS Products:
            -   Unicode and COTS: cots/Readme
#    -   Roadmap: Product-Roadmap.md
#    -   CHEFS Capabilities:
#            -   Functionalities: CHEFS-functionalities.md
#            -   Integrations: Integrations.md
#            -   Accessibility: Accessibility.md
#            -   Form Management: Form-Management.md
#            -   Data Management: Data-Management.md
#            -   Architecture & State Management: Architecture-&-State-Management.md
#    -   CHEFS Components:
#            -   Form Builder Components: Form-Builder-Components.md
#            -   Custom Components: Custom-Components.md
#            -   Examples of CHEFS forms and features: Examples-of-CHEFS-forms-and-features.md
#    -   Developer:
#            -   Contributors: Contributors.md
#            -   Deployment: Deployment.md
#            -   Form.io: Form.io.md
#            -   Developer Additional Resources: Developer-Additional-Resources.md
#

