site_name: "Techniques for supporting Indigenous language characters in B.C. government systems"
site_description: "Resources - code snippets, sample data, high level explanations, links to detailed explanations - to help a systems developer understand how to make sure that a computer system supports the characters and graphemes present in Indigenous languages"
docs_dir: "docs"
repo_url:  https://github.com/bcgov/inclusive-names-service
plugins:
    - techdocs-core
    - ezlinks

markdown_extensions:
    - markdown_inline_mermaid
    - md_in_html
    -   mkpatcher:
            location: patcher.py

#          Example navigation structure shown below. Fill out as appropriate for your content.
nav:
    -   Overview: index.md
    -   Databases:
            - Databases and Unicode: databases/Readme.md
            - Db2: databases/db2/db2.md
            - mysql: databases/mysql/mysql.md
            - Oracle: databases/oracle/oracle.md
            - PostgreSQL: databases/postgresql/postgresql.md
            - SQL Server: databases/sqlserver/sqlserver.md
    -   Programming languages:
            - Programming languages and Unicode: programming_languages/Readme.md
            - C: programming_languages/c/README.md
            - C++: programming_languages/c++/README.md
            - cobol: programming_languages/cobol/README.md
            - go: programming_languages/go/README.md
            - java: programming_languages/java/README.md
            - javascript: programming_languages/javascript/README.md
            - nodejs: programming_languages/nodejs/README.md
            - perl: programming_languages/perl/README.md
            - php: programming_languages/php/README.md
            - python2: programming_languages/python2/README.md
            - python3: programming_languages/python3/README.md
    -   Dataflow Analysis: data_flow_analysis/Readme.md
    -   File Formats:
            - File formats and Unicode: file_formats/Readme.md
            - CSV/Excel: file_formats/csv_excel/csv.md
            - DBF: file_formats/dbf/README.md
    -   Mainframe Systems: mainframe_systems/Readme.md
    -   Web Servers and Web Pages: web_servers_and_web_pages/Readme.md
    -   COTS Products:
            -   Unicode and COTS: cots/Readme.md
            -   Configuring Windows workstations: cots/configuring_workstation.md
    -   Test Data: test_data/Readme.md
    -   Glossary: glossary.md
    -   References: references.md
#    -   Roadmap: Product-Roadmap.md
#    -   CHEFS Capabilities:
#            -   Functionalities: CHEFS-functionalities.md
#            -   Integrations: Integrations.md
#            -   Accessibility: Accessibility.md
#            -   Form Management: Form-Management.md
#            -   Data Management: Data-Management.md
#            -   Architecture & State Management: Architecture-&-State-Management.md
#    -   CHEFS Components:
#            -   Form Builder Components: Form-Builder-Components.md
#            -   Custom Components: Custom-Components.md
#            -   Examples of CHEFS forms and features: Examples-of-CHEFS-forms-and-features.md
#    -   Developer:
#            -   Contributors: Contributors.md
#            -   Deployment: Deployment.md
#            -   Form.io: Form.io.md
#            -   Developer Additional Resources: Developer-Additional-Resources.md
#

